//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taller.apis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacion
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public Nullable<int> meGusta { get; set; }
        public Nullable<int> meDisgusta { get; set; }
        public Nullable<int> vecesCompartido { get; set; }
        public Nullable<bool> esPrivada { get; set; }
    }
}
